sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stiboo2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stiboo2/react-test npm test

after_success:
  - docker build -t stiboo2/multi-client ./client
  - docker build -t stiboo2/multi-nginx ./nginx
  - docker build -t stiboo2/multi-server ./server
  - docker build -t stiboo2/multi-worker ./worker

  # Log in to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker Hub
  - docker push stiboo2/multi-client
  - docker push stiboo2/multi-nginx
  - docker push stiboo2/multi-server
  - docker push stiboo2/multi-worker
